[package]
name = "mark-rs"
version = "0.1.0"
edition = "2021"
authors = ["Mintu Gogogi <mintugogoi567@gmail.com>"]
description = "A Markdown parser implementation in Rust"
license = "MIT"
repository = "https://github.com/Gmin2/mark-rs"

[dependencies]
regex = "1.9"
lazy_static = "1.4"